### ISSUE TITLE
Non field names in CONCAT

### ISSUE THREAD

**Issue by ParadiseStudios** [shadowhand/latitude#101]
While using CONCAT to combine database field names with non database field names, an error will be thrown unless using literal. In order to include a space between two field names, the space must be enclosed within single quotes and double quotes.

```
->select(alias(func('CONCAT', 'fieldNameA', literal("' '"), 'fieldNameB'), 'combinedString'))
```
Is this the best way to include a space or a string in a CONCAT?

**Comment by shadowhand** [comment]
@ParadiseStudios your solution is correct, given that the `' '` is a literal expression that can vary by engine.
