### ISSUE TITLE
Support INSERT IGNORE

### ISSUE THREAD

**Issue by pavarnos** [shadowhand/latitude#105]
Hi. Similar to #47, is there a way to add extra info to an INSERT query eg `INSERT IGNORE tablename...` to ignore duplicate keys?

What do you think about adding a generic `queryFlags()` method to `AbstractQuery`?

**Comment by shadowhand** [comment]
`INSERT IGNORE` is not a standard statement. It could be added to supported databases similarly to how `INSERT ... RETURNING ...` is supported for Postgres.

**Comment by shadowhand** [comment]
Fixed by #106
