### ISSUE TITLE
correcting Query.php for working with MySQL

### ISSUE THREAD

**Issue by rootoor225** [shadowhand/latitude#109]
# change the sql() method like under

```PHP

<?php
declare(strict_types=1);

namespace Latitude\QueryBuilder;

final class Query
{
    /** @var string */
    private $sql;

    /** @var array */
    private $params;

    public function __construct(
        string $sql,
        array $params
    ) {
        $this->sql = $sql;
        $this->params = $params;
    }

    public function sql(): string
    {
        // return $this->sql; // original 
        return str_replace('"', "`",$this->sql); // modified by for MySQL
    }

    public function params(): array
    {
        return $this->params;
    }
}




```

**Comment by rootoor225** [comment]
If not modified, the Query string generated is written with double quote around the columns name or conditions or table name
such as =>          SELECT "id" FROM "users" WHERE "id" = ?     which is misundertood by MySQL compiler or executor

# ERROR 

```php
use Latitude\QueryBuilder\Engine\CommonEngine;
use Latitude\QueryBuilder\QueryFactory;

use function Latitude\QueryBuilder\field;

$factory = new QueryFactory(new CommonEngine());
$query = $factory
    ->select('id', 'username')
    ->from('users')
    ->where(field('id')->eq(5))
    ->compile();

$query->sql(); // SELECT "id" FROM "users" WHERE "id" = ?
$query->params(); // [5]
```

**Comment by shadowhand** [comment]
CommonEngine is incompatible with MYSQL. Use the right engine and everything will work as expected.

**Comment by rootoor225** [comment]
> CommonEngine is incompatible with MYSQL. Use the right engine and everything will work as expected.

ok. Thank u. You should add this note into the documentation.  As Latitude is a huge class, it will be usefull if it's notice in documentation how to use it completly as its the case for Doctrine ORM
