### ISSUE TITLE
Using LIKE for Fields

### ISSUE THREAD

**Issue by JefferiesTube** [shadowhand/latitude#112]
I want to use the LIKE operator for filtering a query. I already found that there is a LikeContains.php but I cannot figure out where to use it properly. I would have expected it to be an options like the other field comparisons. Furthermore, an example in the documentation would help a lot since LIKE is nothing utterly special.

**Comment by shadowhand** [comment]
From [the cheatsheet][1]:

```php
// "username" LIKE '%admin%'
search('username')->contains('admin')
// "first_name" LIKE 'john%'
search('first_name')->begins('john')
// "last_name" NOT LIKE '%rump'
search('last_name')->notEnds('rump')
```

[1]: https://latitude.shadowhand.com/cheatsheet
