### ISSUE TITLE
Computed Columns / Subselects

### ISSUE THREAD

**Issue by JefferiesTube** [shadowhand/latitude#123]
How to add columns into a SELECT query that retreive their value by a subselect (for each row). Sorry, somehow hard to explain. I'll make an example. 

Assume the following two tables:

Table "Designs"
Column | Type
------------ | -------------
DesignID | PRIMARY KEY INT AUTO_INCREMENT
Name | VARCHAR(30) 

Table "Tags"
Column | Type
------------ | -------------
TagID | PRIMARY KEY INT AUTO_INCREMENT
DesignID | FOREIGN KEY 
Tag | VARCHAR(30) 

I want to retrieve a list of all designs and have their tags as a comma-separated list (in a single query). I would usually do something like this:

```
SELECT 
   DesignID, 
   Name, 
   (SELECT ... FROM Tags t WHERE t.DesignID = d.DesignID) Tags 
FROM Designs d
```

How to accomplish this with Latitude?

**Comment by shadowhand** [comment]
Looks like you are using MYSQL, so:

```php
$select = $factory
  ->select('d.DesignID', 'd.name', func('GROUP_CONCAT', 't.Tag'))
  ->from(alias('Designs', 'd'))
  ->join(alias('Tags', 't'), on('t.DesignId', 'd.designId'));
```
