### ISSUE TITLE
How to make scalar subquery (query in select)?

### ISSUE THREAD

**Issue by usefksa** [shadowhand/latitude#139]
Thanks for the great library.
Is it possible to build a scalar subquery ( query in select ) without using join?
I want to build these MySQL queries:
- simple
```sql 
SELECT  posts.id, ( select  tagName FROM  tags  WHERE postTags.postId = posts.id ) AS postTags 
FROM posts WHERE id=1
```

- complex
```sql 
SELECT  posts.id, ( select  GROUP_CONCAT(tagName SEPARATOR "^") FROM  tags  WHERE postTags.postId = posts.id ) AS postTags 
FROM posts WHERE id=1
```

**Comment by shadowhand** [comment]
These queries would be better served by JOINs, which are available in the query builder. The `group_concat` can be done with [func][1] helper.

[1]: https://latitude.shadowhand.com/cheatsheet#functions
