### ISSUE TITLE
JOIN added multiple times with same criteria

### ISSUE THREAD

**Issue by shamim2883** [shadowhand/latitude#156]
There is no check for join if the same table with same criteria is already present or not.
For my use case where i have multiple conditions to add a join. multiple or none conditions can be true. If multiple conditions become true, i see multiple joins added, so i get error.

Can you please add a check so that joins with same table and criteria add only once?

**Comment by shadowhand** [comment]
This is an intentional design choice, because it is perfectly legitimate to JOIN the same table multiple times with different conditions. Not allowing that by forcing every JOIN to a table to have the same criteria would make that impossible.

**Comment by shamim2883** [comment]
May be i was not clear. It is perfectly valid to JOIN same table multiple times with DIFFERENT conditions. Issue is that if we have SAME conditions we can ignore that as that is already added in JOINs.

Invalid Example:
```
$query = $factory
        ->select('u.id', 'u.username')
        ->from( alias('users', 'u' ))
        ->innerJoin( alias( 'employees', 'e' ), on( 'e.u_id', 'u.id' ) )
        ->innerJoin( alias( 'employees', 'e' ), on( 'e.u_id', 'u.id' ) )
```
As you can see employees table are added multiple times (with same alias and on conditions) which will give error. In our use case we have multiple checks to add that inner join which may leads to this condition.

I believe following change will solve it. (May need others checks)

in your `SelectQuery.php` file we have 
```
public function join($table, CriteriaInterface $criteria, string $type = ''): self
    {
        $join = trim(sprintf('%s JOIN', strtoupper($type)));
        $this->joins[] = express("$join %s ON %s", identify($table), $criteria);
        return $this;
    }
```
we can change this to 
```
public function join($table, CriteriaInterface $criteria, string $type = ''): self
    {
        $join = trim(sprintf('%s JOIN', strtoupper($type)));
        $express = express("$join %s ON %s", identify($table), $criteria);
        if( ! in_array( $express, $this->joins ) ){
            $this->joins[] = $express;
        }
        return $this;
    }
```

May you please let us know if this have any side effect?

**Comment by shadowhand** [comment]
That is a reasonable solution to the problem, however I do not believe this is the responsibility of Latitude. Such duplication should be corrected in application code, not here.
