### ISSUE TITLE
Select::from() should accept queries as tables

### ISSUE THREAD

**Issue by yeluolei** [shadowhand/latitude#37]
**Maintainer edit:** Subject was *Can't select from an sub query*.

this is part of my long sql, I want to select from an sub query as table tmp1, but this library doesn't support. and given error indentify

```php
SelectQuery::make()->from(Alias::Make(SelectQuery::make('user', ['id']))->sql(), tmp1)->sql());
```

**Comment by shadowhand** [comment]
```php
Alias::Make(SelectQuery::make('user', ['id']))->sql(), tmp1)
```

would be a PHP warning or error, you would want:

```php
Alias::Make(SelectQuery::make('user', ['id'])), 'tmp1')
```

If that doesn't solve the problem, please provide the full code so I can test it out.

**Comment by yeluolei** [comment]
please try with this sql, the from param is limited to `string` type in your code, I have tried to remove the limitation but still failed.

```
$factory->select(Expression::make('COUNT(DISTINCT %s)', 'tmp0.user_id'))
                ->from(Alias::make(
                    $factory->select('user_id')
                        ->distinct()
                        ->from('user_info')
                        ->where(
                            Conditions::make('new_visitor = 1')
                        ),'tmp0'))->join(
                            Alias::make($factory->select('user_id')
                                ->distinct()
                                ->from('user_info_2')
                                ->where(
                                    Conditions::make('new_visitor = 1')
                                ), 'tmp1')->sql(), Conditions::make('tmp0=tmp1')
                        );
```

**Comment by shadowhand** [comment]
While I am fairly sure you don't need aliases to generate this query, you are correct that `from()` only allows strings. I will treat this issue as a feature request.

**Comment by robertbakker** [comment]
How can I do subquery in `from()` in version 3 ?

The sql output does not give me the braces '()' needed to surround the subquery

Tried with `alias()` and `sprintf("(%s)", $subquerySql)` but no luck there.

**Comment by shadowhand** [comment]
@robertbakker it is not the most obvious thing:

```php
use Latitude\QueryBuilder\Engine\CommonEngine;
use Latitude\QueryBuilder\QueryFactory;

use function Latitude\QueryBuilder\alias;
use function Latitude\QueryBuilder\express;
use function Latitude\QueryBuilder\literal;

$factory = new QueryFactory(new CommonEngine());

$a = $factory->select()->from('users');
$b = $factory->select('u.id')->from(alias(express('(%s)', $a), 'u'));

print_r($b->compile()->sql());
// SELECT "u"."id" FROM (SELECT * FROM "users") AS "u"
```

**Comment by robertbakker** [comment]
Cheers!

**Comment by pavarnos** [comment]
would you accept a pull request to document this? or to create a `subselect()` helper function? I just spent a couple of hours trying to figure this out, eventually stumbling across this comment...

**Comment by shadowhand** [comment]
@pavarnos of course.
