### ISSUE TITLE
Static Analysis as part of Continuous Integration

### ISSUE THREAD

**Issue by paragonie-scott** [shadowhand/latitude#38]
Adding Psalm to the Travis CI test script would offer stronger type-safety guarantees, while also reducing the likelihood of undiscovered bugs.

This is mostly a note for myself; Psalm doesn't work right now because of an unknown error, and I've opened https://github.com/vimeo/psalm/issues/401 to address it.

I suspect that once the Iterator bug is squashed, there will be few (if any) type violations in Latitude, based on a quick scroll through the code.

**Comment by shadowhand** [comment]
Thanks!
