### ISSUE TITLE
use SQL_CALC_FOUND_ROWS

### ISSUE THREAD

**Issue by shamim2883** [shadowhand/latitude#47]
Now we can not use SQL_CALC_FOUND_ROWS
May you please support this?

**Comment by shadowhand** [comment]
What is preventing you from using it? A SELECT with an `Expression` as the column should work fine.

**Comment by shamim2883** [comment]
Thank you for such a quick reply.
With an Expression will create a comma, But there will be no comma with SQL_CALC_FOUND_ROWS

**Comment by shadowhand** [comment]
Ah, right. Would something like this work for you?

```php
$query = $queryFactory->select(/* ... */)->calcFoundRows(true);
```

**Comment by shamim2883** [comment]
yes, i think that will be fine.

**Comment by shamim2883** [comment]
or more generic, any word can be added, eg 
`$query = $queryFactory->select(/* ... */)->addString( string $string );`
$string can be DISTINCT SQL_CALC_FOUND_ROWS etc any word which does not need any comma
