### ISSUE TITLE
Safe with SQLite?

### ISSUE THREAD

**Issue by aitte2** [shadowhand/latitude#48]
This library is amazing. Perfect syntax and no pesky PDO connections.

I just wonder if it's always safe with SQLite? I like to build small toy-project sites with SQLite to avoid a central database.

And I noticed the engine defaults to "Common", which sounds like it may be safe... since I guess "Common" means it avoids using MySQL-based SQL language features...

And since I control the conditions via what conditions I call on this library, I will never risk producing non-SQLite syntax...?

Could you please update the readme to at least mention the state of SQLite compatibility? :-)

**Comment by shadowhand** [comment]
I use Latitude primary with Postgres. Since both Postgres and SQLite implement ANSI SQL, I doubt there would be any issue with using SQLite.

**Comment by aitte2** [comment]
Ah thank you! That was the information I needed to be able to find the answer. Thanks to your "ansi sql" phrase, Google found a list of what ANSI SQL parts that are not implemented in SQLite. I'll post it here for others who find this thread: https://www.sqlite.org/omitted.html

> ### SQL Features That SQLite Does Not Implement
>
> SQLite implements most of the common features of SQL. Rather than try to list all the features of SQL that SQLite does support, it is much easier to list those that it does not. Unsupported features of SQL are shown below.
>
> #### RIGHT and FULL OUTER JOIN
> LEFT OUTER JOIN is implemented, but not RIGHT OUTER JOIN or FULL OUTER JOIN.
> #### Complete ALTER TABLE support
> Only the RENAME TABLE and ADD COLUMN variants of the ALTER TABLE command are supported. Other kinds of ALTER TABLE operations such as DROP COLUMN, ALTER COLUMN, ADD CONSTRAINT, and so forth are omitted.
> #### Complete trigger support
> FOR EACH ROW triggers are supported but not FOR EACH STATEMENT triggers.
> #### Writing to VIEWs
> VIEWs in SQLite are read-only. You may not execute a DELETE, INSERT, or UPDATE statement on a view. But you can create a trigger that fires on an attempt to DELETE, INSERT, or UPDATE a view and do what you need in the body of the trigger.
> #### GRANT and REVOKE
> Since SQLite reads and writes an ordinary disk file, the only access permissions that can be applied are the normal file access permissions of the underlying operating system. The GRANT and REVOKE commands commonly found on client/server RDBMSes are not implemented because they would be meaningless for an embedded database engine.

So as long as I don't call those functions, I'll generate ANSI SQL that will work in SQLite. Lovely! :) Time to use this library! ❤️

**Comment by aitte2** [comment]
Thank you for the clarification! 👍 🐱

**Comment by roomcays** [comment]
There is one thing I've just encountered when using this awesome library with SQLite 3.
When building a `SELECT` query and using:

```php
$query = $this->factory
    ->select('id', 'name')
    ->from('customers')
    ->where(field('active')->eq(true))
    ->compile();
```

the `WHERE` conditions gets translated literaly into following SQL:

```sql
SELECT "id", "name" FROM "customers" WHERE "active" = true
```

There is no named or positional parameters here.
Now please remember, that SQLite does not have a separate boolean storage class. Instead, boolean values are stored as integers `0` (false) and `1` (true).

And now the "coolest": `pdo_sqlite` version **3.27.2** the `true` "value" is considered valid, but for 
**3.20.1** it is not and is throwing an exception:

> Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: true in ...

I have a feeling that this would require separate engine for SQLite that will convert booleans to integers, but currently I don't know how to do it.

**Comment by shadowhand** [comment]
@roomcays if you want to make a PR for this, it requires adding an [Engine][1] and then modifying [Parameter][2] to handle `bool` values differently. The change will require deferring the `null|bool` check to when `sql()` and `params()` are called.

[1]: https://github.com/shadowhand/latitude/tree/master/src/Engine
[2]: https://github.com/shadowhand/latitude/blob/master/src/Partial/Parameter.php

**Comment by roomcays** [comment]
Thanks for the tips. My related PR is #98.
