### ISSUE TITLE
Small bug in Aliases

### ISSUE THREAD

**Issue by aitte2** [shadowhand/latitude#50]
Found a small bug in the feature introduced here:

https://github.com/shadowhand/latitude#aliases
https://github.com/shadowhand/latitude/pull/35/files

The issue is with the alias-code posted here:

```php
use Latitude\QueryBuilder\Alias as a;

$select = SelectQuery::make(
        a::make('id', 'user_id')
    )
    ->from('users');

echo $select->sql();
```

Aliases do not work in the selectquery constructor and not in columns()... ;-)

Result:

`PHP Fatal error:  Uncaught TypeError: preg_split() expects parameter 2 to be string, object given in vendor/latitude/latitude/src/Identifier.php:79`

Using code: dev-master

**Comment by aitte2** [comment]
Likewise, aliases don't work in other places:

`->from(a::make(Database::TABLE_URLS, 'u'));`.

Perhaps this can be solved with some automatic `__toString()` magic?

**Comment by aitte2** [comment]
They work fine where I needed them the most, thankfully! :-D

`$select->innerJoin(a::make($subSelect, 'x'), c::make('u.id = x.urls_id'));`

Great!

By the way, I am loving your library so much. You did the right thing by creating this instead of continuing with Aura. Your syntax is amazing. For example, group/endgroup. Much better than Aura's "function($select){return ...})" syntax etc...

**Comment by shadowhand** [comment]
Right, this is a shortcoming that is related to #37. However, you can use the following to create aliases for tables and columns:

```php
SelectQuery::make(
    'id user_id'
);
```

And it will generate the alias for you.

**Comment by shadowhand** [comment]
See [code here](https://github.com/shadowhand/latitude/blob/05b101ea9932705a41e4e23ca0e76c2d87d6eedc/src/SelectQuery.php#L125) that references [code here](https://github.com/shadowhand/latitude/blob/05b101ea9932705a41e4e23ca0e76c2d87d6eedc/src/Identifier.php#L79-L80).

**Comment by aitte2** [comment]
Thanks again! The workaround is fine, although it involves doing string concatenation manually which makes for some ugly code. It's ok though. But alias support would be better (someday), if possible? 😃

**Comment by shadowhand** [comment]
@aitte2 I'm working on a new version of Latitude that is more expressive. Nearing completion, but no code available. It would look like this:

```php
->from('table') // no alias, or...
->from(identity('table')->as('t'))
```

**Comment by aitte2** [comment]
@shadowhand Beautiful, so it gets rid of the `c::make()` (with the `::make` repetition) syntax in favor of something like `cond()` instead? You have great skill for design! I am blown away by your library. It's incredible and I look forward to the new major version in the future. 👍  😃

**Comment by shadowhand** [comment]
@aitte2 correct. Conditions look like this instead:

```php
identity('country')->in(['JP', 'CN']); // instead of...
c::make('country IN (?)', in::make(['JP', 'CN']);
```

Or to construct a join reference:

```php
$select->join(identity('users')->as('u'), identity('t.user_id')->refs('u.id')); // or...
$select->join(alias('users', 'u'), on('t.user_id', 'u.id')); // shortest possible code
```

**Comment by aitte2** [comment]
My mind is literally being blown. I can't handle the awesomeness of that syntax! It's magic the way it achieves so much with such a natural language. I am so happy I found Latitude. You rock! 😃 Well, take care and good luck and don't wear yourself out. ;-)

**Comment by shadowhand** [comment]
@aitte2 see #52 for progress.
