### ISSUE TITLE
TIME_FORMAT Expression issue

### ISSUE THREAD

**Issue by alouane** [shadowhand/latitude#51]
Hi there

I'm trying to execute the following time format expression:

```php
$this->select(Expression::make('TIME_FORMAT(sessions.start_time, "%H:%i") as time', ), 
 "sessions.title")
        ->where(Conditions::make('date >= ?', date("Y-m-d")))
        ->orderBy(['date', 'ASC'])->limit(8);`
```
but it fails everytime saying :
  ` Return value of Latitude\QueryBuilder\Expression::sql() must be of the type string, boolean returned`

Thanks

**Comment by shadowhand** [comment]
Try this instead:

```php
Expression::make('TIME_FORMAT(%s, "%%H:%%i") AS %s', 'sessions.start_time', 'time');
```

**Comment by alouane** [comment]
Yes, it worked

Thanks for the explanation :)
