### ISSUE TITLE
Postgres using syntax in join

### ISSUE THREAD

**Issue by SebLours** [shadowhand/latitude#54]
I just discover your lib it's just what i'll need!
This issue is just a suggestion for an enhancement.

The `Postgres` join could support the `using` short syntax.

```sql
left join schema.table using (field_id)
```

**Comment by shadowhand** [comment]
It would be very difficult to support that in the current version. Would be pretty easy after #52 lands.

**Comment by shadowhand** [comment]
With version 3.0, you can write:

```php
$select->join('table', express('using %s', identify('field_id'));
```

You could also write a helper function:

```php
function using(string $field): CriteriaInterface
{
    return express('using (%s)', identify($field));
}
```

**Comment by shadowhand** [comment]
There's no good way to add this as a Postgres specific extension, so I would recommend the above if you want a helper function that is different than `on()`.
