### ISSUE TITLE
CONCAT inside an join 'on()'

### ISSUE THREAD

**Issue by riseoflex88** [shadowhand/latitude#64]
```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Latitude\\QueryBuilder\\on() must be of the type string, object given...
```
I'm trying to use the fn() function to do a concat on the join statement. However the fn is returning an object, but on() needs a string. 

How do I pluck the string out of the fn function in the example below?...

```
join(alias('urls', 'u'), on('u.source', fn('CONCAT', 'node/', 'n.nid')));
```

(loving this class so far, the more I throw at it the better it is, great job!)

**Comment by shadowhand** [comment]
`on()` is only a shortcut to `criteria()` for simple JOINs. This should work for more complex situations:

```php
join(alias(...), criteria('%s = %s', identify('u.source'), fn(...));
```

**Comment by shadowhand** [comment]
Did that work for you?

**Comment by riseoflex88** [comment]
Yes, it did thanks. Worked perfectly
