### ISSUE TITLE
Reset groupby 

### ISSUE THREAD

**Issue by riseoflex88** [shadowhand/latitude#71]
Similar to this request: https://github.com/shadowhand/latitude/pull/31

I'd like to be able to reset the groupby setting, is this possible currently? if not, could it be added as a feature? 

I'm building a class which uses latitude as the backbone, but it means I'm not certain what a user will add or remove from the query as it's being built. The groupby is set as a default, but it needs to be overwritten as required. 

The other fields such as orderby were much simpler to see how to amend the latitude code to suggest a fix, but I can't see the same structure with orderby to make a suggestion on how to amend.

**Comment by shadowhand** [comment]
It's not currently possible. This would work as an interim fix:

```php
use Latitude\QueryBuilder\SelectQuery;

\Closure::bind(function () {
    $this->groupBy = null;
}, $select, SelectQuery::class)();
```

http://php.net/manual/en/closure.bind.php

**Comment by riseoflex88** [comment]
Oooh nice, worked perfectly thanks. Thanks for adding to 4.0.0 too!
