### ISSUE TITLE
Interest in schema modification queries?

### ISSUE THREAD

**Issue by lord2800** [shadowhand/latitude#87]
I have a branch where I added basic support for `CREATE TABLE`, `ALTER TABLE`, and `DROP TABLE` schema modification queries (with accompanying tests), would you be interested in it?

**Comment by shadowhand** [comment]
I am not interesting in adding such functionality to Latitude, because there are a number of good migration packages (phinx, doctrine-migrations, etc). Someone could create a separate package that uses Latitude engine to handle schema modification queries.

**Comment by lord2800** [comment]
Good to know, thanks! I'll see about shifting my code into a separate package, then.
