### ISSUE TITLE
Identifier Escaping

### ISSUE THREAD

**Issue by Vansers** [shadowhand/latitude#9]
[https://github.com/shadowhand/latitude#identifier-escaping](https://github.com/shadowhand/latitude#identifier-escaping)

So I have this piece of code....

> $select = SelectQuery::make()->from('transit_feeds')->where(Conditions::make('agencyid = ?', 5));
print_r($select->sql(Identifier::make()));

And I wanted to escape all everything for the sake of security, so the sql returned this and didn't escape the where column...

> SELECT * FROM \`transit_feeds\` WHERE agencyid = ?

However, when as per in the identifier escaping document, it would escape everything it if I put in Identifier::make(), but it's not if you don't define the table AS such as, so I tried putting a letter in...

> $select = SelectQuery::make()->from('transit_feeds f')->where(Conditions::make('f.agencyid = ?', 5));
print_r($select->sql(Identifier::make()));

This would be returned...

> SELECT * FROM \`transit_feeds\` AS \`f\` WHERE \`f\`.\`agencyid\` = ?

I don't mind putting the quotes around in my first example, but I'm just curious if this would be a good practice to have Latitude escaping columns even if the tables aren't defined AS unless I'm missing something here? :flushed:

Cheers!

**Comment by shadowhand** [comment]
Without a fully qualified name, it is not possible to determine what part of the conditional expression `agencyid = ?` is meant to be an identifier. Consider:

```sql
col1 between col2 and ?
```

What part of this should be considered the identifier? It is extremely hard to programmatically determine that `col1` and `col2` are the identifiers, and `between` and `and` are not.

Hence, the easiest (and most efficient) way to correctly determine the identifiers is to only look for fully qualified identifiers.

**Comment by shadowhand** [comment]
I did consider an alternative form of writing conditions:

```php
c::make('col1', 'BETWEEN ? AND ?', [5, 10]); // "col1" BETWEEN 5, 10
c::make('col1', 'BETWEEN', 'col2', 'AND ?', [100]); // "col1" BETWEEN "col2" AND 100
```

But this is (imo) not as easy to understand is much more prone to mistakes.

I'll offer up one more solution, if you really don't want to alias your table and use fully qualified identifiers, you could do something like this:

```php
use Latitude\QueryBuilder\MySQL\Identifier;
use Latitude\QueryBuilder\SelectQuery;
use Latitude\QueryBuilder\Conditions as BaseConditions;

abstract class Conditions
{
    public static function make($statement, array $identifiers, array $params)
    {
        return BaseConditions::make(
            vsprintf(
                $statement,
                array_map([Identifier::make(), 'escapeQualified'], $identifiers)
            ),
            ...$params
        );
    }
}

$select = SelectQuery::make()->from('transit_feeds')->where(
    Conditions::make('%s = ?', ['agencyid'], [5])
);
print_r($select->sql(Identifier::make()));
```
